# Site settings
title: Ashok Portfolio
description: Site about Ashok
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://tanka.la

# User settings
username: Ashok Tankala
user_description: Around â€‹<b>11 years</b> of experience in analysis, design, development, testing, and deployment of web-based applications using multiple technologies. Known for hiring and mentoring great, accomplishment-oriented teams that scale. <b>Managed GirnarSoft Pvt LTD Hyderabad branch</b> over 6 years.
user_title: Deputy Director at CarDekho(GirnarSoft)

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
